"""new tables

Revision ID: da46c96554de
Revises: 
Create Date: 2024-07-06 18:36:26.396507

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "da46c96554de"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "category",
        sa.Column("category", sa.String(length=1024), nullable=False),
        sa.Column("pk", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("pk"),
        sa.UniqueConstraint("category"),
    )
    op.create_table(
        "sold_products",
        sa.Column("count", sa.Integer(), nullable=False),
        sa.Column("first_name", sa.String(), nullable=False),
        sa.Column("last_name", sa.String(), nullable=False),
        sa.Column("phone", sa.String(), nullable=False),
        sa.Column("on_credit", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("pk", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("pk"),
    )
    op.create_table(
        "products",
        sa.Column("name", sa.String(length=1024), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("count", sa.Integer(), nullable=False),
        sa.Column("price", sa.Integer(), nullable=False),
        sa.Column("category_id", sa.Integer(), nullable=False),
        sa.Column("pk", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["category_id"], ["category.pk"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("pk"),
    )
    op.create_table(
        "products_sold",
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column("sold_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["product_id"], ["products.pk"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["sold_id"], ["sold_products.pk"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("product_id", "sold_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("products_sold")
    op.drop_table("products")
    op.drop_table("sold_products")
    op.drop_table("category")
    # ### end Alembic commands ###
